---
title: "Weight of Fish"
author: "Bella Verdin"
date: "Spring 2024"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
```


```{r}
fishdata <- read.csv("Fish.csv")
unique(fishdata$Species)
```



## Perch

```{r}
perchFish <- filter(fishdata, Species=="Perch")
perchFish <- perchFish %>%
  select(-Species)
```


### Best Models

There are best models for all three species. 

### Best Two regressor model

```{r}
perchModel <- lm(Weight~., data=perchFish)
summary(perchModel)
```

```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight ~ .,
               data = perchFish,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")

```
##Which is the best?

```{r}
which.max(summary.out$adjr2)
```

The two best parameters to predict weight would be height and width. 







## Pike

### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements